:GUID: %guid%
:OCP_USERNAME: %ocp_username%
:ACCESS_KEY: %S3_access_key%
:SECRET_KEY: %S3_secret_key%
:markup-in-source: verbatim,attributes,quotes

== Your shared cluster environment

Some more information before we start. +
You Lab has been created on a shared cluster, where the following components or applications have been deployed.

=== OpenShift Data Foundation

ODF provides the object storage needed for this demo. A user account in the ObjectStore (accessible through the Rados Gateway, or RGW) has already been provisioned for you. It will allow you to interact with the RGW through the S3 API to create Object Buckets and configure notifications. +
Your credentials for this access are:

- AWS_ACCESS_KEY: `{ACCESS_KEY}`
- AWS_SECRET_ACCESS_KEY: `{SECRET_KEY}`

Those credentials will be used at various steps, but don't worry, they will be displayed again when needed.

=== Open Data Hub

Open Data Hub has been deployed on the cluster, which will allow you to use on-demand Jupyter Notebooks.

=== AMQ Streams

The AMQ Streams operator has been deployed on the cluster, which will allow an easy deployment of a Kafka Cluster.

=== OpenShift Serverless

The OpenShift Serverless operator has been deployed on the cluster, which will allow an easy deployment of Eventing and Serving components.

=== Grafana

The Grafana operator, a Grafana instance, and a Grafana DataSource for the OpenShift central Prometheus instance, have already been deployed in your project. This has been done in advance as it requires special admin rights, but you will complete the installation with other data source and dashboards.