:GUID: %guid%
:OCP_USERNAME: %ocp_username%
:markup-in-source: verbatim,attributes,quotes

== The Grafana instance

The Grafana instance itself has already been created along with your lab (it was necessary to setup the Prometheus Datasource). So now that we have all the elements in place (Datasources and Dashboards), the operator will reconcile everything and our dashboards will be ready to look at!

=== Verification

In the Console, navigate to Workloads->Pods, verify that the pod `grafana-deployment-xxxxx` is in the Running state. +

You can then navigate to Networking->Routes. Click on the location (URL) for the `grafana-route` route. This will open a new tab in your browser. +
You may have to wait a little bit and refresh though as Grafana is sometimes slow to restart and serve requests after the reconciliation.

In Grafana, on the left side, hover on the "four squares" icon, and select *Manage*. Then click on the folder which should have the name of your project, and click on *XRay Lab*. The dashboard is displayed! Although of course there is nothing happening yet...