:markup-in-source: verbatim,attributes,quotes

== Review

Normally you should have learned a few things in this Lab:

* Create Ceph buckets
* Create bucket notifications
* Deploy and use Kafka
* Deploy and use Serverless functions
* ...

But more importantly, you have seen how you can connect all those components together to create a data pipeline. This example is applied to healthcare, and uses an AI/ML model, but the underlying architecture pattern can be applied anywhere, in a lot of situations. 

If you want to have a look at the code running inside the different containers, head out to the https://github.com/red-hat-data-services/jumpstart-library/tree/main/demo1-xray-pipeline[original repo] for this demo, in the `base_element/containers` folder. In this repo you will also find tons of other information regarding this demo, but also other demos, and fully documented data engineering patterns that you can reuse in your projects!

And if you have further questions, please contact me: gmoutier@redhat.com

Thank you!
