:GUID: %guid%
:OCP_USERNAME: %ocp_username%
:markup-in-source: verbatim,attributes,quotes
:CLUSTER_SUBDOMAIN: %CLUSTER_SUBDOMAIN%

== This is the end...

To stop the demo, we just have to scale down the image-generator back to its original state.

IMPORTANT: Please stop the demo after a few minutes to make sure you don't fill up the cluster with thousands of copies of images... Ceph can https://www.redhat.com/en/blog/scaling-ceph-billion-objects-and-beyond[scale to a billion objects and beyond], but unfortunately we don't have enough storage to do that. 

=== Through the console

On the console, in your main project ({GUID}), navigate to Workloads->Deployment Configs, select `image-generator`. On the `Details` tab, scale it down to zero instance.

=== Through the CLI

You can directly patch the Deployment Config with this command:

[source,bash,subs="{markup-in-source}",role=execute]
----
oc scale deploymentconfig/image-generator --replicas=1
----

=== And now?

Just go to the Grafana dashboard which should still be opened on one of your browser tab (it should be `https://grafana-route-{GUID}.{CLUSTER_SUBDOMAIN}`), and you should see the pipeline stopping (no new images coming in)!